#####################################
# 1. PIECEWISE SYSTEM CONFIGURATION #
#####################################
#
# In this section you will update variables that configure the Piecewise application
# for the remote VM or server.
# 
# Required fields are indicated with the text "# !REQUIRED!" just below the variable name.
# If a field is marked Required, you must enter a value or change the default value.

env: production
# !REQUIRED!
#
# env   Instructs Ansible whether this is a server/VM in development or in production.
#
#       Supported values: production, development
#
#       Use development if you only have an IP address for your server/VM.
#       Use production if you have configured DNS to provide a domain name for your server/VM.

project_name: piecewise
# #DEFAULT#
#
# project_name  
#       The name of your forked repository. This is likely 'piecewise', unless you have renamed
#       the repository after forking it from https://github.com/opentechinsstute.org/piecewise
# TO DO: may no longer be needed. confirm.
#

remote: https://github.com/opentechinstitute
# !REQUIRED!
#
# remote  
#       The URL where your repository is available. You can use any valid git remote. 
#       For example: https://github.com/opentechinstitute 
# TO DO: may no longer be needed. confirm.

piecewise_commit: master
# !REQUIRED!
#
# piecewise_commit
#       Specify any ref (eg. branch, tag, SHA) to be deployed. This ref must be
#       pushed to the remote git_repo before it can be deployed.
# TO DO: may no longer be needed. confirm.

git_repo: "{{ remote }}/{{ project_name }}.git"
# TO DO: may no longer be needed. confirm.

bigquery_project_num: 581276032543
# !REQUIRED!
#
# bigquery_project_num
#       The BigQuery Project Number or Project Name from your project details in the
#       Google Cloud Console at https://console.cloud.google.com
#       This can be the numeric project number or the project name text.

database_name: piecewise
database_user: postgres
database_user_group: postgres
# #DEFAULT#
#
#       These variables define the Postgres database name, user and system group for  
#       the database user. These can be safely left as the default, unless you desire to 
#       change them.

site_fqdn: ipysvenezuela.opentechinstitute.org
# !REQUIRED!
#
# site_fqdn 
#       FQDN stands for Fully Qualified Domain Name. 
#       This value should contain either:
#       - the domain name of your production server, ie: www.mywebsite.com
#       - the IP address of your development or production server, ie: 111.222.333.444
#
#       Use an IP address for development, either on a server/VM on our LAN or a 
#       development server/VM on a cloud service like Linode, GCE, Amazon, etc. 
#
#       Once you have the server's domain name in DNS working, you can use it instead of the IP address.

#-------------------------------------------->>

########################
# 1.1 SSL CERTIFICATES #
########################
# The variables in this section will be used to generate SSL certificates. When 
# deploying to development hosts, the country, state and city are used by openssl to
# generate a self-signed certificate. This is useful when you don't have an DNS name
# set up yet and want to deploy using the host's IP address, or to a server not
# accessible to the Internet.
#

site_contact: critzo@opentechinstitute.org
site_country: US
site_state: District of Columbia
site_city: Washington
site_ou: Open Technology Institute
# !REQUIRED!
#
# site_contact    These variables are provided to enable automatic generation of 
#     _country    SSL certificates, either self-signed for development hosts or
#     ...         valid certificates through the Let's Encrypt CA for production hosts.

self_signed_ssl_cert_path: /etc/ssl/certs/selfsigned.{{ site_fqdn }}.cert
self_signed_ssl_key_path: /etc/ssl/private/selfsigned.{{ site_fqdn }}.key
# #DEFAULT#
#
# When env = 'development', these variables set the directory on the 
# server/VM where self-signed SSL certificates will be saved. 
# In most cases you will not need to change these values from the default.

letsencrypt_ssl_cert_path: /etc/letsencrypt/live/{{ site_fqdn }}/fullchain.pem
letsencrypt_ssl_key_path: /etc/letsencrypt/live/{{ site_fqdn }}/privkey.pem
# #DEFAULT#
#
# When env = 'production', these variables set the directory on the 
# server/VM where Let's Encrypt SSL certificates will be saved.
# In most cases you will not need to change these values from the default.

#################################
# 1.2 DEPLOYMENT FILE LOCATIONS #
#################################
# The variables in this section determine where specific components will be deployed on
# the remote sytem. These can be largely unchanged, unless your system requires 
# different paths.

base_path: /opt
# #DEFAULT#
#
# Where the base files from your repo will be copied on the remote server.

temp_path: "{{ base_path }}/tmp"
# #DEFAULT#
#
# Temporary location on the remote server where files may be extracted temporarily.
# TO DO: may no longer be needed. confirm.

site_path: "{{ base_path }}/piecewise_web"
# #DEFAULT#
#
# Where the website files should be on the server.

#-------------------------------------------->>

###########################################
# 2. MAPPING & AGGREGATION CUSTOMIZATIONS #
###########################################
# The variables in this section define the geographic information needed by the Piecwise
# server backend. They also define the regions to use to calculate aggregate statistics
# for M-Lab data submitted.

########################################
# 2.1 Geodata and Database Information #
########################################
# The section below defines variables used to import your geodata into the database.
# 
# The values you set here assume you have located shapefiles for your region.
# You will need the filenames and knowledge of the field names and datatypes in the
# shapefiles for these variables.
#
# Save the geofiles you intend to use for your Piecewise aggregations of
# M-Lab data in the folder: /local_customizations/geofiles/

shape_file: VEN_adm2-1.shp
# !REQUIRED!
#
# shape_file  The filename of the shapefile Piecewise should use for your aggregations.

dbKey: id_2str
dbKeyDataType: string
shape_projection: "EPSG:4326"
geometry_type: MultiPolygon
layer_name: venezuela_municipalities
aggregation_name: "by_ven_muni"
aggregation_stats_table_name: "ven_muni_stats"
# !REQUIRED!
#
# dbKey             The field name of the unique key in your shape file.
# dbKeyDataType     The data type of dbKey.
# shape_projection  The SRS reprojection/transform to use for this shapefile.
# geometry_type     The geometry type for this layer
# layer_name        The name you wish to be used for this shapefile layer in postgres.
# aggregation_name  The name you wish to use to name this aggregation
# aggregation_stats_table_name    The table name to use for aggregate statistics.

##############################################
# 2.2 Geographic Coordinates and Date Ranges #
##############################################
# Variables in this section define the geographic area and date range you would
# like to use in this Piecewise server. 

map_coordinate_southwest: 
  lat: 0.6475291
  lon: -73.3515581
# !REQUIRED!
#
map_coordinate_northeast: 
  lat: 12.6886
  lon: -59.805666
# !REQUIRED!
#
# The coordinates above define the latitude and longitude for the southwest and 
# northeast corners of a bounding box, defining the region from which you are 
# interested in pulling M-Lab NDT data.
#
# These four variables are used to format the variable map_bounding_box below. 
map_bounding_box: "{{ map_coordinate_southwest.lon }},{{ map_coordinate_southwest.lat }},{{ map_coordinate_northeast.lon }},{{ map_coordinate_northeast.lat }}"
# You do not need to edit the value for map_bounding_box.

map_data_start_date: "Jan 1 2016 00:00:00"
map_data_end_date: "Dec 31 2055 00:00:00"
# !REQUIRED!
#
# map_data_start_date   The range of dates for your server to get M-Lab NDT test data.
# map_data_end_date
#
# During development, we usually set a smaller date range to enable faster ingesting
# of M-Lab data to test the application.
#
# For a production server, it is advisable to set 'map_data_data_end_date'
# to a date well in the future, for example: "Dec 31 2050 00:00:00".

#-------------------------------------------->>

############################
# 3. WEBSITE CUSTOMIZATION #
############################
# The section below defines variables to be used on the website.

######################################
# 3.1 Website Geographic Information #
######################################

topojson_file: VEN_adm2-1.topojson
# !REQUIRED!
#
# topojson_file   The file name of a topojson format geo file that is 
#                 - created using the shapefile defined above
#                 - saved in the folder /local_customizations/geofiles/ 

geoKey: ID_2str
# !REQUIRED!
#
# geoKey    The field name in your topojson file which corresponds to the unique key 
#           in your shapefile. 
#           This is typically the same as dbKey, but in CAPITAL LETTERS.

mapscript_start_year: 2016
mapscript_start_month: 1
# # DEFAULT #
#
# mapscript_start_year  The first year that should be displayed in the 'year' dropdown.
# mapscript_start_month Define the start month in the timeline.

mapscript_base_layer: osm
# # DEFAULT #
#
# mapscript_base_layer  Defines the type of base layer to be used on the map.
#                       Either Mapbox.com or OpenStreetMaps base layers are supported. 
#                       Set mapscript_base_layer to either: 'mapbox' OR 'osm'

mapscript_osm_api_url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
mapscript_mapbox_api_url: ""
# # DEFAULT #
#
# If you would like to customize the OSM base layer API url, for example if you
# are hosting custom maps and tiles on your own tile server, update mapscript_osm_api_url.
# The default OSM url is provided.

# If you are using a Mapbox base layer, set the API URL for your Mapbox tiles above.

mapscript_min_data_points: 2
# # DEFAULT #
#
# Sets the minimum number of tests which must be present in any aggregate area defined by
# your shapefile in order to be displayed on the aggregate website map.

mapscript_zoom_level: 7
# # DEFAULT #
#
# Sets the initial zoom level for the map display.

mapscript_layer_name: "venezuela_municipalities"
mapscript_layer_name_pretty: "Venezuela Municipalities"
# !REQUIRED!
#
# These variables name the map layers on the website. 'mapscript_layer_name' is used as 
# a layer name in the JavaScript code, and 'mapscript_layer_name_pretty' is used in the 
# UI if the layer controls are displayed for the user.

mapscript_json_type: "topojson"
# # DEFAULT #
#
# In the future, support for other types of geodata, such as the geojson format may be
# included in Piecewise. Currently, the mapscript json type should always be 'topojson'. 

# This dictionary of month names/abbreviations lets you configure how month names appear 
# on the website map controls. 
# # DEFAULT #
mapscript_month_names: 
   1: 2016
   2: 2017
   3: 2018
#  1: enero
#  2: febrero
#  3: marzo
#  4: abril
#  5: mayo
#  6: junio
#  7: julio
#  8: agosto
#  9: septiembre
#  10: octubre
#  11: noviembre
#  12: diciembre

####################
# 3.2 Website Form #
####################
# The section below allows you to customize the HTML form preceding the test.
# These values are used to create the HTML form on the webpage, and to set up the
# fields in a database table where submissions are stored. 

# Select lists and text fields are the only types of HTML form elements 
# currently supported. For each type of field, all values are required to be present.
# For example the field definition below is missing db_type and is incorrect:
#    5:
#     advertised_download:
#        field_type: text
#        name: advertised_download
#        id: advertised_download
#        text: "What is your advertised download speed?"
#        size: 3
#        required: no

# Each form field is defined by a nested YAML dictionary structure. 
# Use the structure provided, and change only the values. For example:
#
#  1:
#    isp_user:
#      field_type: select_list
#      db_type: String
#      name: isp_user
#      id: isp_user
#      text: "Select your ISP"
#      options:
#        1:
#          default: "------"
#        2:
#          verizon: "Verizon"
#        3:
#          att: "AT&amp;T"
#        4:
#          comcast: "Comcast"
#        5:
#          tmobile: "T-Mobile"
#        6:
#          other: "Other"
#     required: yes
# 

# Fields are rendered in the order they appear here. Use the first numeric index
# after 'form_fields:' to arrange the order of fields. For example, to reverse the
# display of download and upload speed fields:
# 
# form_fields:
#   ... 
#   5:
#     advertised_upload:
#     ...
#   6:
#     advertised_download:

#form_fields:
#  1:
#    nombre:
#      field_type: text
#      db_type: String
#      name: nombre
#      id: nombre
#      text: "Nombre: "
#      required: yes
#  2:
#    email:
#      field_type: text
#      db_type: String
#      name: email
#      id: email
#      text: "E-mail: " 
#      required: yes
#  3:
#    pais:
#      field_type: text
#      db_type: String
#      name: pais
#      id: pais
#      text: "Pa&#237;s: " 
#      required: yes  
#  4:
#    estado:
#      field_type: text
#      db_type: String
#      name: estado
#      id: estado
#      text: "Estado: " 
#      required: yes  
#  5:
#    ciudad:
#      field_type: text
#      db_type: String
#      name: ciudad
#      id: ciudad
#      text: "Ciudad: " 
#      required: yes   
#  6:
#    provider:
#      field_type: text
#      db_type: String
#      name: provider
#      id: provider
#      text: "Proveedor de servicio de internet: "
#      required: yes
#  7:
#    provider_plan:
#      field_type: text
#      db_type: String
#      name: provider_plan
#      id: provider_plan
#      text: "Plan de navegación contratado (si lo conoce): "
#      required: no
#  8:
#    comments:
#      field_type: text
#      db_type: String
#      name: comments
#      id: comments
#      text: "Dudas y Comentarios: "
#      required: no

# !REQUIRED!
#

####################
# 3.3 Website Text #
####################
# The section below allows you to customize various text and other elements of the website.

site_name: "Test de velocidad de IPYS"
# #DEFAULT#
#
# Defines the HTML page title element

intro_text: >
  Ayúdanos a construir el mapa de la navegación de internet en Venezuela

instructions_text: >
  IPYS Venezuela junto a MLAB realizan una radiografía de la calidad de la conexión en 
  Venezuela. Súmate a esta iniciativa corriendo este test de velocidad desde tu conexión 
  fija o móvil.    
# #DEFAULT#
#
# Defines the heading text that precedes the HTML survey form, provided to users
# before they may take the test.

consent_message: >
  Entiendo que los datos recopilados de esta prueba se anonimizar&#225;n y agregar&#225;n para 
  su publicaci&#243;n.
# #DEFAULT#
#
# Defines the message displayed next to the consent checkbox.

# The variables below define the messages and labels provided to the user before and 
# after the test.
run_test_heading: "Pon a prueba tu velocidad!"
test_result_heading: "Sus resultados de prueba"
download_result_label: "Velocidad de Descarga:"
download_result_unit: "Mbps"
upload_result_label: "Velocidad de carga:"
upload_result_unit: "Mbps"
rtt_result_label: "Tiempo m&#237;nimo de ida y vuelta:"
rtt_result_unit: "ms"
thank_you_heading: "Gracias!"
thank_you_message: >
  Los resultados de sus pruebas se combinar&#225;n con otros y aparecer&#225;n en el mapa pronto.
# #DEFAULT#
#

# 'next_action_' variables define the action items present to the user after they run the test.
next_action_message: "Qu&#233; quieres hacer después?"
next_action_show_map_text: "Ver todos los resultados hasta la fecha en un mapa de Venezuela"
next_action_learn_about_text: "Aprenda m&#225;s sobre esta prueba y c&#243;mo mejorar su velocidad"
next_action_learn_about_link: "http://ipysvenezuela.org/navegarconlibertad/"
next_action_social_share_text: "Compartir en las redes sociales"
# #DEFAULT#
#

# 'social_share_' variables define the links to be used for social sharing actions.
#
# If you set any of these to 'none', they will be excluded from the website.
# If you don't want any social share options, set all of the items below to 'none'
# and also set 'next_action_social_share_text' to 'none' (without quotes) above.
social_share_twitter: "http://twitter.com/share?url=http://ipysvenezuela.org/navegarconlibertad&text=Probé%20mi%20velocidad%20de%20Internet%20con%20la%20prueba%20de%20velocidad%20IPYS%20de%20M-Lab&via=ipysvenezuela"
social_share_gplus: "none" #"https://plus.google.com/share?url=http://www.seattle.gov/broadband-speed-test"
social_share_facebook: "http://www.facebook.com/sharer/sharer.php?u=https://www.facebook.com/IpysVenezuela/?fref=ts"
social_share_stumbleupon: "none" #"http://www.stumbleupon.com/submit?url=http://www.seattle.gov/broadband-speed-test&title=I%20tested%20my%20Internet%20speeds%20with%20the%20Seattle%20Broadband%20Speed%20Test"
social_share_reddit: "none" #"http://reddit.com/submit?url=http://www.seattle.gov/broadband-speed-test&title=I%20tested%20my%20Internet%20speeds%20with%20the%20Seattle%20Broadband%20Speed%20Test"
social_share_linkedin: "none" #"http://www.linkedin.com/shareArticle?url=http://www.seattle.gov/broadband-speed-test&title=I%20tested%20my%20Internet%20speeds%20with%20the%20Seattle%20Broadband%20Speed%20Test&summary=I%20tested%20my%20Internet%20speeds%20with%20the%20Seattle%20Broadband%20Speed%20Test&source=http://www.seattle.gov/broadband-speed-test"
social_share_email: "none" #"mailto:?subject=Take%20the%20Seattle%20Broadband%20Speed Test&body=I%20just%20took%20the%20Seattle%20Broadband%20Speed%20Test,%20and%20you%20should%20too!%20Take%20the%20test%20and%20contribute%20to%20a%20map%20of%20broadband%20speeds%20across%20the%20city. http://www.seattle.gov/broadband-speed-test"
# #DEFAULT#
#

# 'icon_' and 'mapview_icon_' variables define the text accompanying the icons in the user interface.
#
# 'icon_' variables set the text values and '?' link accompanying icons on the initial map display.
icon_test_label: "Toma la prueba de velocidad"
icon_test_alt_text: "Toma la prueba de velocidad"
icon_browse_label: "Navega por el mapa"
icon_browse_alt_text: "Navega por el mapa"
icon_learn_label: "Aprende m&#225;s"
icon_learn_alt_text: "Aprenda m&#225;s sobre esta prueba."
icon_learn_link: "http://ipysvenezuela.org/navegarconlibertad/"
# #DEFAULT#
#

# 'mapview_icon_' variables set the text values and '?' link on the mapview display
mapview_icon_test_alt_text: "Toma la prueba de velocidad"
mapview_icon_learn_alt_text: "Aprenda m&#225;s sobre esta prueba."
mapview_icon_learn_link: "http://ipysvenezuela.org/navegarconlibertad/"
# #DEFAULT#
#

# The two variables below control where Leaflet map controls are placed in the UI. 
# They should remain unchanged for now. More work on positioning for Leaflet elements will follow.
mapcontrols_zoom_pos: topright
mapcontrols_legend_pos: bottomleft
# #DEFAULT#
#
#-------------------------------------------->>
