---
- hosts: all
  tasks:
    - include: system_tasks.yml
      become: yes
      become_method: sudo
    - include: user_tasks.yml
    - include: seattle_tasks.yml
      become: yes
      become_method: sudo
